### ISSUE TITLE
Box Sizing

### ISSUE THREAD

**Issue by danstramer** [pojome/one-click-accessibility#28]
Hello,
The plugin adds in it's style sheet the following rule:
`
*, ::before, ::after {
    box-sizing: border-box;
}
`
which causes layout issues for the site.
Could you remove if for the next release?
Thanks
Dan

**Comment by arielk** [comment]
Can you share with us a link to this page or steps to reproduce this situation?

**Comment by arielk** [comment]
Fixed: https://github.com/pojome/one-click-accessibility/pull/57/commits/708a19f378c899a6c10725fbe6cda28a612b0f89
