### ISSUE TITLE
One Click Accesibility translate

### ISSUE THREAD

**Issue by studiojorisbudel** [pojome/one-click-accessibility#32]
I would like to know how to translate One Click Accesibility?
I tried it with Loco translate and WPML but this does not work..

Looking for Dutch translation.
Thanks in advance!

Kind regards,
from Joris

**Comment by dharmist** [comment]
@studiojorisbudel 
Hi there! Did you ever manage to solve this on your own, or did you move on to another plugin?

**Comment by studiojorisbudel** [comment]
@dharmist Yes, discovered it was possible to translate within the plugin, did not look thoroughly enough! 😉
