### ISSUE TITLE
new issue with broken link

### ISSUE THREAD

**Issue by dudurom** [pojome/one-click-accessibility#36]
hey guys,
![80861537_602906077176671_1329770674260017152_n](https://user-images.githubusercontent.com/59249697/71469274-5707d280-27d1-11ea-981d-448860656c92.png)

i discover an issue.

it seems that there is a broken link.
XXXX/X#content

a id="pojo-a11y-skip-content" class="pojo-skip-link pojo-skip-content" tabindex="1" accesskey="s" href="#content">דילוג לתוכן</a

i cant find this link in front end, but when i do ctrl+U, i can see the link.

what can i do?

**Comment by arielk** [comment]
This issue has been resolved in Elementor v2.1.0

Feel free to update

Thanks!
