### ISSUE TITLE
Images Removed

### ISSUE THREAD

**Issue by gilcags** [pojome/one-click-accessibility#41]
Is this a bug? 

1. The images are removed when in High Contrast, Negative Contrast, and Light Background.
2. When Increasing Text, it does not increase the Header Text.

**Comment by arielk** [comment]
Can you please share with us a link to the page with this issue?

**Comment by gilcags** [comment]
This is the link staging.hoainitiative.org

**Comment by arielk** [comment]
Note that when inserting images as a background these options replace all backgrounds with a dark or light background, to allow users who need this option better accessibility so that you do not see your images but in terms of accessibility it is good behavior.
