### ISSUE TITLE
Glitch on page load

### ISSUE THREAD

**Issue by 147Dev** [pojome/one-click-accessibility#42]
Hi there, I hope you can help.

I am using the WordPress plugin and I love it! I am however having a problem on page load; it seems to load it for a couple of seconds without css, do you know of any way that I can fix this? 

Thanks in advance,
Matt.

**Comment by arielk** [comment]
Can you please share with us a link to the page with this issue?

**Comment by 147Dev** [comment]
It seems to be F.O.U.T.

https://www.147webdev.com





________________________________

**Comment by arielk** [comment]
I do not see any problem on your site, what am I missing?

**Comment by 147Dev** [comment]
Hi Ariel,

It was a very ugly F.O.U.T. problem, I think it was a plugin conflict; I have resolved the problem.

Thank you,
Matt



________________________________
