### ISSUE TITLE
Icon failure

### ISSUE THREAD

**Issue by blurbox** [pojome/one-click-accessibility#47]
I've installed the One click accessibility to my client's Elementor Pro site but all that appears is a small blue box.  I have selected and Icon from the choices but no icon appears.  
Any ideas how to get the icon to appear so that people actually know this feature is available on the site? 
<img width="952" alt="Screenshot 2020-09-21 at 12 30 37" src="https://user-images.githubusercontent.com/71642665/93761956-9ea77780-fc06-11ea-9ae9-f0fb01851ff0.png">

**Comment by arielk** [comment]
Can you please share with us a link to the page with this issue?

**Comment by renufka** [comment]
Hello I have this same problem. I've installed the One click accessibility to my site but I see only a small box whithout any icon. I have selected Icon from the choices but no icon appears.
Please help me how to show the icon?  my website: https://instytutgk.pl/ 

![without-icon](https://user-images.githubusercontent.com/74925830/99998280-b8a83680-2dbe-11eb-8ad7-e610e14d2150.png)

**Comment by arielk** [comment]
Your theme adds CSS code that causes this issue, in the meantime please add this line to your Customizer > CSS to resolve this issue:
`#pojo-a11y-toolbar .pojo-a11y-toolbar-toggle a svg {max-width: none;width: 32px;}`

**Comment by arielk** [comment]
Fixed: https://github.com/pojome/one-click-accessibility/pull/57/commits/708a19f378c899a6c10725fbe6cda28a612b0f89
