### ISSUE TITLE
Icon disappeared

### ISSUE THREAD

**Issue by renufka** [pojome/one-click-accessibility#50]
Hi! I have problem with icon view. I've installed the One click accessibility to my site but I see only a small box whithout any icon. I have selected Icon from the choices but no icon appears.
Please help me how to show the icon?  my website: https://instytutgk.pl/ 

![without-icon](https://user-images.githubusercontent.com/74925830/99998280-b8a83680-2dbe-11eb-8ad7-e610e14d2150.png) # @ @arielk

**Comment by arielk** [comment]
Merge https://github.com/pojome/one-click-accessibility/issues/47
