### ISSUE TITLE
Code for non WordPress websites

### ISSUE THREAD

**Issue by MusselwhiteMarketing** [pojome/one-click-accessibility#89]
First time user of Github. Created an account and logged in specifically for One-Click-Accessibility. Do you have or provide code for non WordPress websites?

**Comment by arielk** [comment]
One-Click-Accessibility is a plugin designed specifically for WordPress websites to improve their accessibility for people with disabilities. Currently, we do not have a version of the plugin for non-WordPress websites. However, we are constantly exploring new opportunities to expand the reach of our plugin and make the web more accessible for everyone.

Thanks.
